### ISSUE TITLE
HTML-CSS->Analytics

### ISSUE THREAD

**Issue by Dhanush-2605** [meerhamzadev/Hacktoberfest#11]
![image](https://user-images.githubusercontent.com/90703523/193787081-ba8e4284-81f2-4272-a8b2-6ed2b6852860.png)
hi, can I work on this section?

**Comment by meerhamzadev** [comment]
@Dhanush-2605 You are good to go. Don't forget to follow the [README guidelines](https://github.com/meerhamzadev/Hacktoberfest/blob/main/README.md).

**Comment by Dhanush-2605** [comment]
@meerhamzadev  sure, thank you

**Comment by Dhanush-2605** [comment]
![image](https://user-images.githubusercontent.com/90703523/193824931-9b28eade-6b45-46f0-aa06-f51827899039.png)

@meerhamzadev is this ok can i make PR or do i need to change anything in this?

**Comment by meerhamzadev** [comment]
Great go for PR
