### ISSUE TITLE
Flutter-module->signin screen

### ISSUE THREAD

**Issue by dragoonoid** [meerhamzadev/Hacktoberfest#12]

**Comment by meerhamzadev** [comment]
@dragoonoid Would you like to work on this issue?

**Comment by dragoonoid** [comment]
> @dragoonoid Would you like to work on this issue?

yes i would like to add the auth part in flutter.

**Comment by meerhamzadev** [comment]
I'm assigning SignIn page to you. Although the proper authentication functionality is not required. You can still add it if you like. SignUp page is already assigned so no need to develop that. You are good to go. Don't forget to follow the [README guidelines](https://github.com/meerhamzadev/Hacktoberfest/blob/main/README.md).

**Comment by dragoonoid** [comment]
> I'm assigning SignIn page to you. Although the proper authentication functionality is not required. You can still add it if you like. SignUp page is already assigned so no need to develop that. You are good to go. Don't forget to follow the [README guidelines](https://github.com/meerhamzadev/Hacktoberfest/blob/main/README.md).

So i just have to implement the sign in screen? Not the signup and reset password one?

**Comment by meerhamzadev** [comment]
You can implement the reset password but not signup because it's already assigned.

**Comment by dragoonoid** [comment]
> You can implement the reset password but not signup because it's already assigned.

Ok,thanks.
