### ISSUE TITLE
 HTML/CSS -> Value Section

### ISSUE THREAD

**Issue by pragyamittal0** [meerhamzadev/Hacktoberfest#13]
Please assign this section to me!

**Comment by meerhamzadev** [comment]
Hey, can you please add a screenshot of the session

**Comment by pragyamittal0** [comment]
![image](https://user-images.githubusercontent.com/69578414/193802668-e33fa50a-4cd2-4b0b-a22a-2e8de95713c9.png)

**Comment by meerhamzadev** [comment]
@pragyamittal0 Sorry this section is already assigned. Issue #9. You can work on something else.

**Comment by pragyamittal0** [comment]
![image](https://user-images.githubusercontent.com/69578414/193803624-7719b7e4-db29-407a-932c-c1639c292619.png)

Can I work on this one?

**Comment by pragyamittal0** [comment]
Sure, thanks
