### ISSUE TITLE
Module: HTML/CSS  Page/Section: footer and contact form

### ISSUE THREAD

**Issue by MAYANK816** [meerhamzadev/Hacktoberfest#23]

**Comment by meerhamzadev** [comment]
Hey these two issues are already assigned.

**Comment by MAYANK816** [comment]
But I think no one is making contact form so could I make that ?

**Comment by meerhamzadev** [comment]
No, Actually someone has already created contact form and opened a pull request. You can checkout other modules. React & flutter module has plenty of unassigned things. You can improve the existing contact section or You can wait for a while once all pull request of this template has merged. A new template will replaced this one.

**Comment by MAYANK816** [comment]
okay buddy then could you assign me the react modules, I already opened the react module you can check that  and let me know.
