### ISSUE TITLE
HTMP/CSS module-> Home Page

### ISSUE THREAD

**Issue by sumitkr2000** [meerhamzadev/Hacktoberfest#7]
Hey @meerhamzadev I want to work on this isuue please assign me this issue thank you !

**Comment by meerhamzadev** [comment]
Hey kindly mention the section of HTML/CSS module where you want to work.

**Comment by sumitkr2000** [comment]
@meerhamzadev Can you tell me what changesI have to do?

**Comment by Ayushjain373** [comment]
HTML/CSS Module want to work

**Comment by Ayushjain373** [comment]
@meerhamzadev  Html/CSS Module want to work

**Comment by meerhamzadev** [comment]
@sumitkr2000 You can work on any section of the html/css template like home section, contact section, testimonials section etc. To also left room for others, you can work only on one section. Kindly reply this message by mentioning your desired section.

**Comment by meerhamzadev** [comment]
@Ayushjain373 kindly open a separate issue and mention your desired section on which you want to work.

**Comment by sumitkr2000** [comment]
@meerhamzadev I want to work on contact section. Kindly assign me this issue. Do I have to make another file or make changes in the index.html itself?

**Comment by meerhamzadev** [comment]
@sumitkr2000 contact section and customer review section is already assigned. You can work on something else. Its totally upto you whether you create a separate file or work on index.html file.

**Comment by Ayushjain373** [comment]
Sir issue #9
Name ayush jain

I cloned the project and after can you please tell me next step
I don't get that the checkout step

**Comment by sumitkr2000** [comment]
@meerhamzadev I can work on home page. Do I have to make exact copy as shown in template?

**Comment by meerhamzadev** [comment]
@sumitkr2000 No, just your effort matters. You are good to go.
