### ISSUE TITLE
Html/CSS Module - > Contact Section

### ISSUE THREAD

**Issue by Ayushjain373** [meerhamzadev/Hacktoberfest#9]
Html/CSS Module
I want to work Contact section

**Comment by meerhamzadev** [comment]
@Ayushjain373 I'm assigning contact section to you. You are good to go. Don't forget to follow the [README guidelines](https://github.com/meerhamzadev/Hacktoberfest/blob/main/README.md).

**Comment by meerhamzadev** [comment]
@Ayushjain373 message here whenever you face any issue. The checkout step is actually for creating a new branch. In your case checkout would be like this
git checkout -b html-css/contact-page

This command will create a new branch and also switch your controls to that branch.

**Comment by Ayushjain373** [comment]
Ok thanks
